services:
  - type: web
    name: studyverse
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    # Force use of gthread for generic WebSocket support without patches
    startCommand: gunicorn --worker-class gthread --threads 50 -w 1 --timeout 120 --bind 0.0.0.0:$PORT --preload --log-level debug --capture-output --error-logfile - app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: WEB_CONCURRENCY
        value: 1




